export const wIterable = "iterable"
export const wSync = "sync"
export const wAsync = `a${wSync}`
export const wSymbol = "symbol"
export const wpAsync = `(${wAsync})`
export const wAsyncIterable = `${wAsync} ${wIterable}`
export const wpAsyncIterable = `${wpAsync} iterable`
export const wObject = "object"
export const wBigInt = "bigint"
export const wIterator = "iterator"
export const wFunction = typeof isNaN as "function"
export const wAnonymous = "<anonymous>"
export const wPromise = "Promise"
export const wInteger = "integer"
export const wArgument = "argument"
export const wReturn = "return"
export const wConstructor = "constructor"
export const wConversion = "conversion"
export const wButGot = "but got"
export const wInput = "input"
export const wSeq = "seq"
export const wAseq = "aseq"
export const wBe = "be"
export const wCalledWith = "called with"
export const wArguments = "arguments"
export const wDoddle = "doddle"
export const wString = "string"
export const wError = "error"
export const wT = "true"
export const wF = "false"
export const wArray = "array"
export const wInf = "Infinity"
export const wToString = "toString"
export const wBefore = "before" as const
export const wPositive = "positive" as const
export const wNegative = "negative" as const
export const wAfter = "after" as const
export const wBoth = "both" as const
export const wUndefined = `${undefined}`
export const syAsyncIterator = Symbol.asyncIterator
export const syIterator = Symbol.iterator
export const syToStringTag = Symbol.toStringTag
export const wDescription = "description" as const
export const wLength = "length" as const
export const wStart = "start" as const
export const wTimes = "times" as const
export const wEnd = "end" as const
export const wIndex = "index" as const
export const wProjection = "projection" as const
export const wKeyProjection = "keyProjection" as const
export const wAction = "action" as const
export const wCount = "count" as const
export const wHandler = "handler" as const
export const wReverse = "reverse" as const
export const wSeparator = "separator" as const
export const wStage = "stage" as const
export const wKvpProjection = "kvpProjection" as const
export const wThrower = "thrower" as const
export const wSize = "size" as const
export const wReducer = "reducer" as const
export const wPredicate = "predicate" as const
export const wSkipCount = "skipCount" as const
export const wNull = "null" as const
export const wcSeq = "Seq" as const
export const wcASeq = "ASeq" as const
export const wPrototype = "prototype" as const
