name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.18.0
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: COREPACK
        run: corepack enable
      - name: USE ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "22.18.0"
          cache: yarn
          registry-url: "https://registry.yarnpkg.com"

      - name: SET YARN VERSION
        run: yarn set version stable
      - name: INSTALL
        run: yarn install --immutable
      - name: BUILD
        run: yarn run build
      - name: CHECK STYLE
        run: yarn run lint:check
      - name: TEST
        run: yarn run test:coverage
      - name: UPLOAD COVERAGE(codacy)
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          CODACY_USERNAME: GregRos
          CODACY_PROJECT_NAME: doddle
          CODACY_ORGANIZATION_PROVIDER: gh
      - name: SETUP TOKEN
        run: 'echo "npmAuthToken: ${NPM_TOKEN}" >> ~/.yarnrc.yml'
      - name: PACKAGING SCRIPT
        run: yarn run package
      - name: PUBLISH
        run: yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
